./set_eav_attribute.py compute-etcd00054.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00055.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00056.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00057.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00058.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00024.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00025.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00026.us-rno-a.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd3002.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd3003.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd3004.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd3005.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd3006.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master3011.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master3012.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master3013.lv7.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00059.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00060.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00061.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00062.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00063.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00034.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00036.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00037.us-las-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00064.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00065.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00066.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00067.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-etcd00068.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00032.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00033.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
./set_eav_attribute.py compute-master00035.us-rno-b.dc001.prod.box.net PROVISIONING_ROLES k8s::idle
